import Head from 'next/head'
import { ConnectWallet } from "@thirdweb-dev/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Traderoid</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        {/* <ConnectWallet theme={"dark"} modalSize={"compact"}/> */}

      </main>
    </>
  )
}

